-- Migration 006: Seed content data (from app.js)
-- Hiragana, Katakana, Vocabulary, Kanji

-- ── Hiragana ─────────────────────────────────────────────────
INSERT INTO content_kana (type, character, romaji) VALUES
('hiragana','あ','a'),('hiragana','い','i'),('hiragana','う','u'),('hiragana','え','e'),('hiragana','お','o'),
('hiragana','か','ka'),('hiragana','き','ki'),('hiragana','く','ku'),('hiragana','け','ke'),('hiragana','こ','ko'),
('hiragana','さ','sa'),('hiragana','し','shi'),('hiragana','す','su'),('hiragana','せ','se'),('hiragana','そ','so'),
('hiragana','た','ta'),('hiragana','ち','chi'),('hiragana','つ','tsu'),('hiragana','て','te'),('hiragana','と','to'),
('hiragana','な','na'),('hiragana','に','ni'),('hiragana','ぬ','nu'),('hiragana','ね','ne'),('hiragana','の','no'),
('hiragana','は','ha'),('hiragana','ひ','hi'),('hiragana','ふ','fu'),('hiragana','へ','he'),('hiragana','ほ','ho'),
('hiragana','ま','ma'),('hiragana','み','mi'),('hiragana','む','mu'),('hiragana','め','me'),('hiragana','も','mo'),
('hiragana','や','ya'),('hiragana','ゆ','yu'),('hiragana','よ','yo'),
('hiragana','ら','ra'),('hiragana','り','ri'),('hiragana','る','ru'),('hiragana','れ','re'),('hiragana','ろ','ro'),
('hiragana','わ','wa'),('hiragana','を','wo'),('hiragana','ん','n'),
('hiragana','が','ga'),('hiragana','ぎ','gi'),('hiragana','ぐ','gu'),('hiragana','げ','ge'),('hiragana','ご','go'),
('hiragana','ざ','za'),('hiragana','じ','ji'),('hiragana','ず','zu'),('hiragana','ぜ','ze'),('hiragana','ぞ','zo'),
('hiragana','だ','da'),('hiragana','ぢ','di'),('hiragana','づ','du'),('hiragana','で','de'),('hiragana','ど','do'),
('hiragana','ば','ba'),('hiragana','び','bi'),('hiragana','ぶ','bu'),('hiragana','べ','be'),('hiragana','ぼ','bo'),
('hiragana','ぱ','pa'),('hiragana','ぴ','pi'),('hiragana','ぷ','pu'),('hiragana','ぺ','pe'),('hiragana','ぽ','po');

-- ── Katakana ─────────────────────────────────────────────────
INSERT INTO content_kana (type, character, romaji) VALUES
('katakana','ア','a'),('katakana','イ','i'),('katakana','ウ','u'),('katakana','エ','e'),('katakana','オ','o'),
('katakana','カ','ka'),('katakana','キ','ki'),('katakana','ク','ku'),('katakana','ケ','ke'),('katakana','コ','ko'),
('katakana','サ','sa'),('katakana','シ','shi'),('katakana','ス','su'),('katakana','セ','se'),('katakana','ソ','so'),
('katakana','タ','ta'),('katakana','チ','chi'),('katakana','ツ','tsu'),('katakana','テ','te'),('katakana','ト','to'),
('katakana','ナ','na'),('katakana','ニ','ni'),('katakana','ヌ','nu'),('katakana','ネ','ne'),('katakana','ノ','no'),
('katakana','ハ','ha'),('katakana','ヒ','hi'),('katakana','フ','fu'),('katakana','ヘ','he'),('katakana','ホ','ho'),
('katakana','マ','ma'),('katakana','ミ','mi'),('katakana','ム','mu'),('katakana','メ','me'),('katakana','モ','mo'),
('katakana','ヤ','ya'),('katakana','ユ','yu'),('katakana','ヨ','yo'),
('katakana','ラ','ra'),('katakana','リ','ri'),('katakana','ル','ru'),('katakana','レ','re'),('katakana','ロ','ro'),
('katakana','ワ','wa'),('katakana','ヲ','wo'),('katakana','ン','n'),
('katakana','ガ','ga'),('katakana','ギ','gi'),('katakana','グ','gu'),('katakana','ゲ','ge'),('katakana','ゴ','go'),
('katakana','ザ','za'),('katakana','ジ','ji'),('katakana','ズ','zu'),('katakana','ゼ','ze'),('katakana','ゾ','zo'),
('katakana','バ','ba'),('katakana','ビ','bi'),('katakana','ブ','bu'),('katakana','ベ','be'),('katakana','ボ','bo'),
('katakana','パ','pa'),('katakana','ピ','pi'),('katakana','プ','pu'),('katakana','ペ','pe'),('katakana','ポ','po');

-- ── Vocabulary ───────────────────────────────────────────────
INSERT INTO content_vocabulary (japanese, reading, english, category, jlpt_level) VALUES
-- Greetings (N5)
('こんにちは','Konnichiwa','Hello / Good afternoon','Greetings',5),
('おはよう','Ohayou','Good morning','Greetings',5),
('こんばんは','Konbanwa','Good evening','Greetings',5),
('さようなら','Sayounara','Goodbye','Greetings',5),
('ありがとう','Arigatou','Thank you','Greetings',5),
('すみません','Sumimasen','Excuse me / Sorry','Greetings',5),
('はじめまして','Hajimemashite','Nice to meet you','Greetings',5),
('どういたしまして','Douitashimashite','You''re welcome','Greetings',5),
('よろしくお願いします','Yoroshiku onegaishimasu','Please treat me well','Greetings',5),
('お元気ですか','Ogenki desu ka','How are you?','Greetings',5),
('またね','Mata ne','See you','Greetings',5),
-- Anime (N5-N3)
('仲間','Nakama','Comrade / Friend / Crewmate','Anime',4),
('夢','Yume','Dream','Anime',4),
('力','Chikara','Power / Strength','Anime',5),
('勝利','Shouri','Victory','Anime',3),
('運命','Unmei','Destiny / Fate','Anime',3),
('心','Kokoro','Heart / Mind / Soul','Anime',4),
('魂','Tamashii','Soul / Spirit','Anime',3),
('戦士','Senshi','Warrior / Fighter','Anime',3),
('剣','Ken','Sword','Anime',3),
('魔法','Mahou','Magic','Anime',3),
('変身','Henshin','Transformation','Anime',3),
('必殺技','Hissatsu waza','Special finishing move','Anime',2),
('覚悟','Kakugo','Resolve / Determination','Anime',2),
('挑戦','Chousen','Challenge','Anime',3),
('最強','Saikyou','The strongest','Anime',3),
('敵','Teki','Enemy','Anime',4),
('守る','Mamoru','To protect','Anime',4),
('倒す','Taosu','To defeat','Anime',4),
-- Daily Life (N5)
('食べる','Taberu','To eat','Daily Life',5),
('飲む','Nomu','To drink','Daily Life',5),
('寝る','Neru','To sleep','Daily Life',5),
('行く','Iku','To go','Daily Life',5),
('来る','Kuru','To come','Daily Life',5),
('見る','Miru','To see / watch','Daily Life',5),
('聞く','Kiku','To hear / listen','Daily Life',5),
('話す','Hanasu','To speak / talk','Daily Life',5),
('水','Mizu','Water','Daily Life',5),
('ご飯','Gohan','Rice / Meal','Daily Life',5),
('学校','Gakkou','School','Daily Life',5),
('仕事','Shigoto','Work / Job','Daily Life',5),
('友達','Tomodachi','Friend','Daily Life',5),
('家族','Kazoku','Family','Daily Life',5),
('時間','Jikan','Time','Daily Life',5),
('今日','Kyou','Today','Daily Life',5),
('明日','Ashita','Tomorrow','Daily Life',5),
-- Emotions (N5-N4)
('好き','Suki','Like / Love','Emotions',5),
('嫌い','Kirai','Dislike / Hate','Emotions',5),
('嬉しい','Ureshii','Happy / Glad','Emotions',5),
('悲しい','Kanashii','Sad','Emotions',5),
('怖い','Kowai','Scary / Afraid','Emotions',5),
('楽しい','Tanoshii','Fun / Enjoyable','Emotions',5),
('怒る','Okoru','To get angry','Emotions',5),
('愛','Ai','Love','Emotions',4),
('寂しい','Sabishii','Lonely','Emotions',4),
('緊張','Kinchou','Nervous / Tension','Emotions',4),
('安心','Anshin','Relief / Peace of mind','Emotions',4),
('驚く','Odoroku','To be surprised','Emotions',4);

-- ── Kanji ────────────────────────────────────────────────────
INSERT INTO content_kanji (character, meaning, on_reading, kun_reading, stroke_count, jlpt_level) VALUES
('日','Sun / Day','ニチ/ジツ','ひ/か',4,5),
('月','Moon / Month','ゲツ/ガツ','つき',4,5),
('火','Fire','カ','ひ',4,5),
('水','Water','スイ','みず',4,5),
('木','Tree / Wood','モク/ボク','き/こ',4,5),
('金','Gold / Money','キン/コン','かね/かな',8,5),
('土','Earth / Soil','ド/ト','つち',3,5),
('山','Mountain','サン','やま',3,5),
('川','River','セン','かわ',3,5),
('田','Rice field','デン','た',5,5),
('人','Person','ジン/ニン','ひと',2,5),
('口','Mouth','コウ/ク','くち',3,5),
('手','Hand','シュ','て',4,5),
('目','Eye','モク/ボク','め',5,5),
('耳','Ear','ジ','みみ',6,5),
('力','Power / Strength','リョク/リキ','ちから',2,5),
('心','Heart / Mind','シン','こころ',4,4),
('愛','Love','アイ','めで',13,3),
('夢','Dream','ム','ゆめ',13,3),
('魂','Soul','コン','たましい',14,2),
('剣','Sword','ケン','つるぎ',10,2),
('龍','Dragon','リュウ/リョウ','たつ',16,1);
