-- Migration 007: Anime vocabulary expansion (~500 words)
-- Sources: onetoone-school.com scripts + curated anime vocabulary

INSERT INTO content_vocabulary (japanese, reading, english, category, jlpt_level) VALUES

-- ── From onetoone-school.com scripts ──────────────────────────────
('厨二病', 'Chuunibyou', 'Eighth-grader syndrome / Adolescent delusions', 'Anime', 3),
('呪われし', 'Norowareshi', 'Cursed (dramatic/literary)', 'Anime', 2),
('奈落', 'Naraku', 'Abyss / Underworld', 'Anime', 2),
('終焉', 'Shuuen', 'Final end / Demise', 'Anime', 2),
('世界の理', 'Sekai no kotowari', 'Laws / Principles of the world', 'Anime', 1),
('歪む', 'Yugamu', 'To warp / Distort', 'Anime', 2),
('滅ぼす', 'Horobosu', 'To destroy / Annihilate', 'Anime', 2),
('闇', 'Yami', 'Darkness', 'Anime', 3),
('影', 'Kage', 'Shadow', 'Anime', 4),
('足掻く', 'Agaku', 'To struggle / Writhe', 'Anime', 2),
('引きずり込む', 'Hikizurikomu', 'To drag into / Pull in', 'Anime', 1),
('あやかし', 'Ayakashi', 'Supernatural being / Spirit', 'Anime', 2),
('封じる', 'Fujiru', 'To seal / Bind (supernatural)', 'Anime', 2),
('供物', 'Kumotsu', 'Offering / Sacrifice', 'Anime', 2),
('正義の味方', 'Seigi no mikata', 'Ally of justice / Hero', 'Anime', 3),
('傷だらけ', 'Kizudarake', 'Covered in wounds / Battle-scarred', 'Anime', 3),
('降伏', 'Koufuku', 'Surrender', 'Anime', 3),
('突入', 'Totsunyuu', 'Storm in / Break in', 'Anime', 2),
('逃げ場', 'Nigeba', 'Escape route / Way out', 'Anime', 3),
('最後通告', 'Saigo tsuukoku', 'Final ultimatum / Last warning', 'Anime', 2),
('異世界転生', 'Isekai tensei', 'Reincarnation in another world', 'Anime', 3),
('生き延びる', 'Ikinobiru', 'To survive', 'Anime', 3),

-- ── Battle / Combat (戦闘) ──────────────────────────────────────────
('斬撃', 'Zangeki', 'Slash attack', 'Battle', 2),
('奥義', 'Ougi', 'Secret technique / Ultimate move', 'Battle', 2),
('連撃', 'Rengeki', 'Combo attack', 'Battle', 2),
('突撃', 'Totsugeki', 'Charge / Assault', 'Battle', 3),
('爆発', 'Bakuhatsu', 'Explosion', 'Battle', 3),
('衝撃', 'Shougeki', 'Impact / Shockwave', 'Battle', 3),
('破壊', 'Hakai', 'Destruction', 'Battle', 3),
('撃破', 'Gekiha', 'Defeat / Destroy', 'Battle', 2),
('反撃', 'Hangeki', 'Counterattack', 'Battle', 2),
('奇襲', 'Kishuu', 'Surprise attack', 'Battle', 2),
('撤退', 'Tettai', 'Retreat / Withdrawal', 'Battle', 3),
('援軍', 'Engun', 'Reinforcements', 'Battle', 2),
('作戦', 'Sakusen', 'Operation / Tactics', 'Battle', 3),
('任務', 'Ninmu', 'Mission / Duty', 'Battle', 3),
('標的', 'Hyouteki', 'Target', 'Battle', 2),
('武器', 'Buki', 'Weapon', 'Battle', 4),
('盾', 'Tate', 'Shield', 'Battle', 4),
('鎧', 'Yoroi', 'Armor', 'Battle', 2),
('弓', 'Yumi', 'Bow (weapon)', 'Battle', 4),
('矢', 'Ya', 'Arrow', 'Battle', 4),
('槍', 'Yari', 'Spear / Lance', 'Battle', 2),
('血', 'Chi', 'Blood', 'Battle', 4),
('傷', 'Kizu', 'Wound / Injury', 'Battle', 4),
('命', 'Inochi', 'Life', 'Battle', 3),
('生死', 'Seishi', 'Life and death', 'Battle', 2),
('斬る', 'Kiru', 'To slash / Cut', 'Battle', 4),
('突く', 'Tsuku', 'To thrust / Stab', 'Battle', 4),
('蹴る', 'Keru', 'To kick', 'Battle', 4),
('殴る', 'Naguru', 'To punch / Strike', 'Battle', 4),
('避ける', 'Sakeru', 'To dodge / Avoid', 'Battle', 3),
('防ぐ', 'Fusegu', 'To block / Defend', 'Battle', 3),
('構える', 'Kamaeru', 'To take a stance / Ready oneself', 'Battle', 2),
('気合い', 'Kiai', 'Fighting spirit / Battle cry', 'Battle', 3),
('闘志', 'Toushi', 'Fighting spirit / Will to fight', 'Battle', 2),
('戦略', 'Senryaku', 'Strategy', 'Battle', 2),
('指揮', 'Shiki', 'Command / Leadership', 'Battle', 2),
('包囲', 'Houi', 'Encirclement', 'Battle', 2),
('刀', 'Katana', 'Katana / Japanese sword', 'Battle', 3),
('短刀', 'Tantou', 'Dagger / Short knife', 'Battle', 2),
('手裏剣', 'Shuriken', 'Shuriken / Throwing star', 'Battle', 3),
('爆弾', 'Bakudan', 'Bomb', 'Battle', 3),
('慎重', 'Shinchou', 'Cautious / Careful', 'Battle', 3),
('迎撃', 'Geigeki', 'Interception', 'Battle', 2),
('討伐', 'Toubatsu', 'Subjugation / Extermination', 'Battle', 2),
('全滅', 'Zenmetsu', 'Total annihilation / Wipe out', 'Battle', 2),
('必死', 'Hisshi', 'Desperate / With all one''s might', 'Battle', 3),
('叫ぶ', 'Sakebu', 'To shout / Scream', 'Battle', 4),
('震える', 'Furueru', 'To tremble / Shiver', 'Battle', 3),

-- ── Powers / Abilities (能力) ──────────────────────────────────────
('能力', 'Nouryoku', 'Ability / Power', 'Anime', 3),
('才能', 'Sainou', 'Talent / Gift', 'Anime', 3),
('超能力', 'Chouryoku', 'Psychic power / Superpower', 'Anime', 3),
('精神力', 'Seishinryoku', 'Mental strength / Willpower', 'Anime', 2),
('気', 'Ki', 'Ki / Life energy / Spirit force', 'Anime', 4),
('オーラ', 'Oura', 'Aura', 'Anime', 3),
('レベル', 'Reberu', 'Level', 'Anime', 4),
('経験値', 'Keikenchi', 'Experience points / EXP', 'Anime', 3),
('スキル', 'Sukiru', 'Skill', 'Anime', 4),
('魔力', 'Maryoku', 'Magic power / Mana', 'Anime', 3),
('魔術', 'Majutsu', 'Sorcery / Magic arts', 'Anime', 2),
('呪文', 'Jumon', 'Spell / Incantation', 'Anime', 2),
('召喚', 'Shoukan', 'Summoning', 'Anime', 2),
('封印', 'Fuuin', 'Seal / Sealing (power)', 'Anime', 2),
('結界', 'Kekkai', 'Barrier / Magic barrier', 'Anime', 2),
('加護', 'Kago', 'Divine protection / Blessing', 'Anime', 2),
('呪い', 'Noroi', 'Curse', 'Anime', 3),
('毒', 'Doku', 'Poison', 'Anime', 4),
('炎', 'Honoo', 'Flame / Blaze', 'Anime', 3),
('氷', 'Koori', 'Ice', 'Anime', 4),
('雷', 'Kaminari', 'Thunder / Lightning', 'Anime', 4),
('覚醒', 'Kakusei', 'Awakening / Awakened state', 'Anime', 2),
('進化', 'Shinka', 'Evolution', 'Anime', 3),
('強化', 'Kyouka', 'Enhancement / Power-up', 'Anime', 3),
('解放', 'Kaihou', 'Release / Liberation', 'Anime', 3),
('限界突破', 'Genkai toppa', 'Breaking the limit / Beyond limits', 'Anime', 2),
('全力', 'Zenryoku', 'Full power / All-out', 'Anime', 3),
('本気', 'Honki', 'Serious mode / Earnest', 'Anime', 3),
('切り札', 'Kirifuda', 'Trump card', 'Anime', 3),
('蘇生', 'Sosei', 'Resurrection', 'Anime', 2),
('回復', 'Kaifuku', 'Recovery / Healing', 'Anime', 3),
('念力', 'Nenriki', 'Telekinesis / Psychokinesis', 'Anime', 2),
('変形', 'Henkei', 'Transformation / Shape change', 'Anime', 3),

-- ── Characters / Roles (キャラクター) ─────────────────────────────
('勇者', 'Yuusha', 'Hero / Brave warrior', 'Anime', 3),
('魔王', 'Maou', 'Demon Lord / Dark Lord', 'Anime', 3),
('賢者', 'Kenja', 'Sage / Wise man', 'Anime', 2),
('騎士', 'Kishi', 'Knight', 'Anime', 3),
('忍者', 'Ninja', 'Ninja', 'Anime', 4),
('侍', 'Samurai', 'Samurai', 'Anime', 4),
('海賊', 'Kaizoku', 'Pirate', 'Anime', 3),
('冒険者', 'Boukensha', 'Adventurer', 'Anime', 3),
('盗賊', 'Touzoku', 'Thief / Bandit', 'Anime', 3),
('魔女', 'Majo', 'Witch', 'Anime', 3),
('精霊', 'Seirei', 'Spirit / Elemental', 'Anime', 2),
('悪魔', 'Akuma', 'Demon / Devil', 'Anime', 3),
('天使', 'Tenshi', 'Angel', 'Anime', 3),
('神', 'Kami', 'God / Deity', 'Anime', 4),
('竜', 'Ryuu', 'Dragon', 'Anime', 3),
('妖精', 'Yousei', 'Fairy / Elf', 'Anime', 3),
('吸血鬼', 'Kyuuketsuki', 'Vampire', 'Anime', 3),
('亡霊', 'Bourei', 'Ghost / Specter', 'Anime', 2),
('怪物', 'Kaibutsu', 'Monster', 'Anime', 3),
('魔物', 'Mamono', 'Magical beast / Demon creature', 'Anime', 2),
('王', 'Ou', 'King', 'Anime', 4),
('女王', 'Joou', 'Queen', 'Anime', 3),
('皇帝', 'Koutei', 'Emperor', 'Anime', 2),
('姫', 'Hime', 'Princess', 'Anime', 4),
('王子', 'Ouji', 'Prince', 'Anime', 4),
('英雄', 'Eiyuu', 'Hero / Epic hero', 'Anime', 3),
('剣士', 'Kenshi', 'Swordsman / Sword fighter', 'Anime', 3),
('武士', 'Bushi', 'Warrior / Samurai', 'Anime', 3),
('浪人', 'Rounin', 'Ronin / Masterless samurai', 'Anime', 2),
('式神', 'Shikigami', 'Spirit familiar / Shikigami', 'Anime', 2),
('使い魔', 'Tsukaima', 'Familiar (magical companion)', 'Anime', 2),

-- ── Story Elements (ストーリー) ────────────────────────────────────
('真実', 'Shinjitsu', 'Truth', 'Anime', 3),
('秘密', 'Himitsu', 'Secret', 'Anime', 3),
('謎', 'Nazo', 'Mystery / Riddle', 'Anime', 3),
('伝説', 'Densetsu', 'Legend', 'Anime', 3),
('予言', 'Yogen', 'Prophecy', 'Anime', 2),
('記憶', 'Kioku', 'Memory', 'Anime', 3),
('過去', 'Kako', 'The past', 'Anime', 3),
('未来', 'Mirai', 'The future', 'Anime', 4),
('試練', 'Shiren', 'Ordeal / Trial', 'Anime', 2),
('宿命', 'Shukumei', 'Fate / Destiny (inescapable)', 'Anime', 2),
('使命', 'Shimei', 'Mission / Calling', 'Anime', 2),
('誓い', 'Chikai', 'Oath / Vow', 'Anime', 2),
('約束', 'Yakusoku', 'Promise', 'Anime', 4),
('裏切り', 'Uragiri', 'Betrayal', 'Anime', 3),
('復讐', 'Fukushuu', 'Revenge', 'Anime', 2),
('犠牲', 'Gisei', 'Sacrifice', 'Anime', 2),
('奇跡', 'Kiseki', 'Miracle', 'Anime', 3),
('絶望', 'Zetsubou', 'Despair', 'Anime', 2),
('希望', 'Kibou', 'Hope', 'Anime', 3),
('光', 'Hikari', 'Light', 'Anime', 4),
('真の力', 'Shin no chikara', 'True power / Real strength', 'Anime', 2),
('陰謀', 'Inbou', 'Conspiracy / Plot', 'Anime', 2),
('罠', 'Wana', 'Trap / Snare', 'Anime', 3),
('計画', 'Keikaku', 'Plan / Scheme', 'Anime', 3),
('契約', 'Keiyaku', 'Contract / Pact', 'Anime', 3),
('正体', 'Shoutai', 'True identity', 'Anime', 3),
('仮面', 'Kamen', 'Mask', 'Anime', 3),
('素顔', 'Sugao', 'True face / Real self', 'Anime', 2),
('遺言', 'Yuigon', 'Last words / Final will', 'Anime', 2),
('誇り', 'Hokori', 'Pride', 'Anime', 3),
('名誉', 'Meiyo', 'Honor', 'Anime', 2),
('恥', 'Haji', 'Shame / Disgrace', 'Anime', 3),

-- ── Isekai / Fantasy (異世界) ──────────────────────────────────────
('転生', 'Tensei', 'Reincarnation', 'Fantasy', 3),
('異世界', 'Isekai', 'Another world / Parallel world', 'Fantasy', 3),
('チート', 'Chiito', 'Cheat / Overpowered ability', 'Fantasy', 3),
('無双', 'Musou', 'Unmatched / Dominating strength', 'Fantasy', 2),
('最弱', 'Saijaku', 'The weakest', 'Fantasy', 3),
('ダンジョン', 'Danjon', 'Dungeon', 'Fantasy', 3),
('魔法陣', 'Mahouji', 'Magic circle / Magic array', 'Fantasy', 2),
('転移', 'Ten''i', 'Teleportation', 'Fantasy', 2),
('鑑定', 'Kantei', 'Appraisal (skill)', 'Fantasy', 2),
('合成', 'Gousei', 'Synthesis / Crafting', 'Fantasy', 2),
('依頼', 'Irai', 'Quest / Request / Commission', 'Fantasy', 3),
('ギルド', 'Girudo', 'Guild', 'Fantasy', 3),
('パーティー', 'Paatii', 'Party (adventurer group)', 'Fantasy', 4),
('ボス', 'Bosu', 'Boss (enemy)', 'Fantasy', 4),
('レア', 'Rea', 'Rare', 'Fantasy', 4),
('神器', 'Jingi', 'Divine artifact / Sacred treasure', 'Fantasy', 2),
('聖剣', 'Seiken', 'Holy sword', 'Fantasy', 2),
('魔剣', 'Maken', 'Demon sword / Cursed sword', 'Fantasy', 2),
('装備', 'Soubi', 'Equipment / Gear', 'Fantasy', 3),
('ポーション', 'Pooshon', 'Potion', 'Fantasy', 4),
('即死', 'Sokushi', 'Instant death', 'Fantasy', 2),
('無限', 'Mugen', 'Infinite / Boundless', 'Fantasy', 3),
('永遠', 'Eien', 'Eternity / Forever', 'Fantasy', 3),
('不滅', 'Fumetsu', 'Immortal / Indestructible', 'Fantasy', 2),
('不死', 'Fushi', 'Undying / Immortality', 'Fantasy', 2),
('王国', 'Oukoku', 'Kingdom', 'Fantasy', 3),
('帝国', 'Teikoku', 'Empire', 'Fantasy', 2),
('城', 'Shiro', 'Castle', 'Fantasy', 4),
('神殿', 'Shinden', 'Temple / Sacred hall', 'Fantasy', 2),
('廃墟', 'Haikyo', 'Ruins / Abandoned place', 'Fantasy', 2),
('大陸', 'Tairiku', 'Continent', 'Fantasy', 3),

-- ── Supernatural / Occult (超自然) ────────────────────────────────
('霊', 'Rei', 'Spirit / Ghost', 'Supernatural', 3),
('幽霊', 'Yuurei', 'Ghost', 'Supernatural', 3),
('妖怪', 'Youkai', 'Yokai / Monster spirit', 'Supernatural', 3),
('霊力', 'Reiryoku', 'Spiritual power', 'Supernatural', 2),
('浄化', 'Jouka', 'Purification', 'Supernatural', 2),
('除霊', 'Jorei', 'Exorcism', 'Supernatural', 2),
('憑依', 'Hyoui', 'Spirit possession', 'Supernatural', 1),
('禁忌', 'Kinki', 'Taboo / Forbidden', 'Supernatural', 2),
('鬼', 'Oni', 'Oni / Demon ogre', 'Supernatural', 3),
('天国', 'Tengoku', 'Heaven / Paradise', 'Supernatural', 3),
('地獄', 'Jigoku', 'Hell', 'Supernatural', 3),
('煉獄', 'Rengoku', 'Purgatory', 'Supernatural', 2),
('輪廻', 'Rinne', 'Reincarnation cycle / Samsara', 'Supernatural', 1),
('封魔', 'Fuuma', 'Demon sealing', 'Supernatural', 1),
('御札', 'Ofuda', 'Talisman / Paper charm', 'Supernatural', 2),
('数珠', 'Juzu', 'Prayer beads', 'Supernatural', 2),
('半妖', 'Han''you', 'Half-demon', 'Supernatural', 2),

-- ── Emotions / Feelings (感情) ────────────────────────────────────
('燃える', 'Moeru', 'To burn with passion', 'Emotions', 3),
('熱い', 'Atsui', 'Hot / Passionate / Fired up', 'Emotions', 4),
('冷たい', 'Tsumetai', 'Cold (personality) / Distant', 'Emotions', 4),
('強がる', 'Tsuyogaru', 'To act tough / Put on a brave face', 'Emotions', 3),
('泣く', 'Naku', 'To cry', 'Emotions', 4),
('笑う', 'Warau', 'To laugh / Smile', 'Emotions', 4),
('感動', 'Kandou', 'Being moved / Deeply touched', 'Emotions', 3),
('興奮', 'Koufun', 'Excitement', 'Emotions', 3),
('恐怖', 'Kyoufu', 'Fear / Terror', 'Emotions', 3),
('憎しみ', 'Nikushimi', 'Hatred', 'Emotions', 2),
('怨み', 'Urami', 'Grudge / Resentment', 'Emotions', 2),
('歓喜', 'Kanki', 'Great joy / Exultation', 'Emotions', 2),
('安堵', 'Ando', 'Relief / Reassurance', 'Emotions', 2),
('驚愕', 'Kyougaku', 'Astonishment / Shock', 'Emotions', 2),
('苦しみ', 'Kurushimi', 'Suffering / Anguish', 'Emotions', 3),
('孤独', 'Kodoku', 'Loneliness / Solitude', 'Emotions', 3),
('迷い', 'Mayoi', 'Hesitation / Uncertainty', 'Emotions', 3),
('葛藤', 'Kattou', 'Inner conflict / Struggle', 'Emotions', 2),
('後悔', 'Koukai', 'Regret', 'Emotions', 3),
('執念', 'Shuunen', 'Obsession / Tenacity', 'Emotions', 2),
('罪悪感', 'Zaiakunkan', 'Sense of guilt', 'Emotions', 2),
('狂気', 'Kyouki', 'Madness / Insanity', 'Emotions', 2),
('トラウマ', 'Torauma', 'Trauma', 'Emotions', 3),
('ドキドキ', 'Dokidoki', 'Heart pounding / Nervous excitement', 'Emotions', 4),
('懺悔', 'Zange', 'Confession / Repentance', 'Emotions', 2),

-- ── Romance (恋愛) ─────────────────────────────────────────────────
('告白', 'Kokuhaku', 'Confession of love', 'Romance', 3),
('片思い', 'Kataomoi', 'Unrequited love', 'Romance', 3),
('初恋', 'Hatsukoi', 'First love', 'Romance', 3),
('失恋', 'Shitsuren', 'Heartbreak / Lost love', 'Romance', 3),
('再会', 'Saikai', 'Reunion', 'Romance', 3),
('デート', 'Deeto', 'Date (romantic)', 'Romance', 4),
('恋人', 'Koibito', 'Lover / Partner', 'Romance', 3),
('婚約', 'Kon''yaku', 'Engagement (to marry)', 'Romance', 3),
('結婚', 'Kekkon', 'Marriage', 'Romance', 4),
('嫉妬', 'Shitto', 'Jealousy', 'Romance', 3),
('恥ずかしい', 'Hazukashii', 'Embarrassing / Shy', 'Romance', 4),
('ツンデレ', 'Tsundere', 'Tsundere (cold-then-warm personality)', 'Romance', 3),
('ヤンデレ', 'Yandere', 'Yandere (obsessively loving)', 'Romance', 3),
('ラブコメ', 'Rabukome', 'Romantic comedy (genre)', 'Romance', 4),
('別れ', 'Wakare', 'Breakup / Parting', 'Romance', 3),
('両思い', 'Ryoumoi', 'Mutual love', 'Romance', 3),

-- ── Relationships / Social (人間関係) ─────────────────────────────
('ライバル', 'Raibaru', 'Rival', 'Anime', 4),
('親友', 'Shin''yuu', 'Best friend', 'Anime', 3),
('戦友', 'Sen''yuu', 'Comrade-in-arms', 'Anime', 2),
('師匠', 'Shishou', 'Master / Teacher', 'Anime', 3),
('弟子', 'Deshi', 'Disciple / Apprentice', 'Anime', 3),
('同志', 'Doushi', 'Comrade / Ally', 'Anime', 2),
('相棒', 'Aibou', 'Partner / Buddy', 'Anime', 3),
('組織', 'Soshiki', 'Organization', 'Anime', 3),
('幹部', 'Kanbu', 'Executive / High-ranking member', 'Anime', 2),
('首領', 'Shuryou', 'Leader / Boss (of group)', 'Anime', 2),
('手下', 'Teshita', 'Underling / Subordinate', 'Anime', 2),
('裏切り者', 'Uragirimono', 'Traitor', 'Anime', 3),
('分身', 'Bunshin', 'Clone / Doppelganger', 'Anime', 2),
('同盟', 'Doumei', 'Alliance', 'Anime', 2),

-- ── School Life (学園) ────────────────────────────────────────────
('生徒会', 'Seitokai', 'Student council', 'School', 3),
('文化祭', 'Bunkasai', 'School cultural festival', 'School', 3),
('体育祭', 'Taiikusai', 'Sports day / Athletic festival', 'School', 3),
('部活', 'Bukatsu', 'Club activity', 'School', 3),
('委員長', 'Iinchou', 'Class representative', 'School', 3),
('転校生', 'Tenkousei', 'Transfer student', 'School', 3),
('修学旅行', 'Shuugakuryokou', 'School field trip', 'School', 3),
('放課後', 'Houkago', 'After school', 'School', 3),
('卒業', 'Sotsugyou', 'Graduation', 'School', 4),
('受験', 'Juken', 'Entrance exam', 'School', 3),
('合格', 'Goukaku', 'Passing an exam / Acceptance', 'School', 3),
('制服', 'Seifuku', 'School uniform', 'School', 3),
('授業', 'Jugyou', 'Class / Lesson', 'School', 4),
('宿題', 'Shukudai', 'Homework', 'School', 4),
('成績', 'Seiseki', 'Grades / Academic results', 'School', 3),

-- ── Common Anime Phrases (決め台詞) ──────────────────────────────
('まさか', 'Masaka', 'No way! / Impossible! / Unbelievable!', 'Anime', 3),
('やはり', 'Yahari', 'As I thought / Just as expected', 'Anime', 3),
('なぜだ', 'Naze da', 'Why?! / Why is this happening?!', 'Anime', 4),
('うるさい', 'Urusai', 'Shut up! / You''re so loud!', 'Anime', 4),
('馬鹿野郎', 'Baka yarou', 'You idiot! / You fool!', 'Anime', 3),
('許さない', 'Yurusanai', 'I will never forgive you!', 'Anime', 3),
('諦めない', 'Akiramenai', 'I won''t give up!', 'Anime', 3),
('絶対に', 'Zettai ni', 'Absolutely / No matter what', 'Anime', 3),
('行くぞ', 'Iku zo', 'Let''s go! / Here we go!', 'Anime', 4),
('待て', 'Mate', 'Wait! / Stop right there!', 'Anime', 4),
('逃がさない', 'Nigasanai', 'I won''t let you escape!', 'Anime', 3),
('何者だ', 'Nanimono da', 'Who are you?!', 'Anime', 3),
('俺に任せろ', 'Ore ni makasero', 'Leave it to me! / I''ve got this!', 'Anime', 3),
('覚悟はいいか', 'Kakugo wa ii ka', 'Are you prepared? / Ready yourself!', 'Anime', 2),
('黙れ', 'Damare', 'Silence! / Be quiet!', 'Anime', 3),
('助けて', 'Tasukete', 'Help me! / Save me!', 'Anime', 4),
('逃げろ', 'Nigero', 'Run! / Flee now!', 'Anime', 4),
('もう終わりだ', 'Mou owari da', 'It''s over / This is the end!', 'Anime', 3),
('嘘だろ', 'Uso daro', 'You''re kidding! / That can''t be true!', 'Anime', 3),
('信じられない', 'Shinjirarenai', 'Unbelievable! / I can''t believe it!', 'Anime', 3),

-- ── Descriptors / Adjectives (形容詞) ────────────────────────────
('強大', 'Kyoudai', 'Powerful / Mighty', 'Anime', 2),
('偉大', 'Idai', 'Great / Magnificent', 'Anime', 2),
('邪悪', 'Jaaku', 'Evil / Wicked', 'Anime', 2),
('神聖', 'Shinsei', 'Sacred / Holy', 'Anime', 2),
('不気味', 'Bukimi', 'Eerie / Uncanny / Creepy', 'Anime', 3),
('儚い', 'Hakanai', 'Fleeting / Transient / Ephemeral', 'Anime', 2),
('壮大', 'Soudai', 'Grand / Epic / Magnificent', 'Anime', 2),
('残酷', 'Zankoku', 'Cruel / Brutal', 'Anime', 2),
('無情', 'Mujou', 'Merciless / Heartless', 'Anime', 2),
('純粋', 'Junsui', 'Pure / Innocent', 'Anime', 2),
('凶悪', 'Kyouaku', 'Ferocious / Villainous', 'Anime', 2),
('無敵', 'Muteki', 'Invincible / Undefeatable', 'Anime', 3),
('孤高', 'Kokou', 'Solitary greatness / Standing alone at the top', 'Anime', 1),
('神速', 'Shinsoku', 'Godlike speed / Blinding speed', 'Anime', 1),

-- ── Sports / Competition (スポーツ) ──────────────────────────────
('全国大会', 'Zenkoku taikai', 'National championship', 'Sports', 3),
('決勝', 'Kesshou', 'Final (match)', 'Sports', 3),
('準決勝', 'Junkesshou', 'Semifinal', 'Sports', 2),
('予選', 'Yosen', 'Preliminary / Qualifier', 'Sports', 3),
('逆転', 'Gyakuten', 'Reversal / Comeback', 'Sports', 3),
('引き分け', 'Hikiwake', 'Draw / Tie', 'Sports', 3),
('失格', 'Shikkaku', 'Disqualification', 'Sports', 2),
('道場', 'Doujou', 'Dojo / Training hall', 'Sports', 3),
('修行', 'Shugyou', 'Training / Discipline', 'Sports', 2),
('武道', 'Budou', 'Martial arts / The way of the warrior', 'Sports', 3),
('剣道', 'Kendou', 'Kendo (Japanese sword art)', 'Sports', 3),
('空手', 'Karate', 'Karate', 'Sports', 3),
('忍術', 'Ninjutsu', 'Ninjutsu / Ninja arts', 'Sports', 2),

-- ── Traditional Japan (時代劇) ─────────────────────────────────────
('天下', 'Tenka', 'The whole realm / The land', 'Traditional', 2),
('幕府', 'Bakufu', 'Shogunate', 'Traditional', 2),
('武士道', 'Bushidou', 'Way of the samurai / Bushido', 'Traditional', 2),
('忠義', 'Chuugi', 'Loyalty / Faithfulness', 'Traditional', 2),
('義理', 'Giri', 'Duty / Obligation', 'Traditional', 3),
('大名', 'Daimyou', 'Feudal lord', 'Traditional', 2),
('切腹', 'Seppuku', 'Ritual suicide (honorable death)', 'Traditional', 2),
('義侠', 'Gikyou', 'Chivalry / Righteous heroism', 'Traditional', 1),
('大義', 'Taigi', 'Great cause / Just cause', 'Traditional', 1),

-- ── Sci-fi / Mecha (SF) ───────────────────────────────────────────
('ロボット', 'Robotto', 'Robot', 'Sci-fi', 4),
('メカ', 'Meka', 'Mecha / Mechanical', 'Sci-fi', 3),
('パイロット', 'Pairotto', 'Pilot', 'Sci-fi', 4),
('出撃', 'Shutsugeki', 'Sortie / Launch (into battle)', 'Sci-fi', 2),
('合体', 'Gattai', 'Combination / Merging (robots)', 'Sci-fi', 2),
('サイボーグ', 'Saiboogu', 'Cyborg', 'Sci-fi', 3),
('人工知能', 'Jinkou chinou', 'Artificial intelligence / AI', 'Sci-fi', 2),
('仮想現実', 'Kasou genjitsu', 'Virtual reality / VR', 'Sci-fi', 2),
('ビーム', 'Biimu', 'Beam (attack)', 'Sci-fi', 4),

-- ── Philosophy / Ideology (哲学) ──────────────────────────────────
('正義', 'Seigi', 'Justice', 'Anime', 3),
('善悪', 'Zen''aku', 'Good and evil', 'Anime', 2),
('真理', 'Shinri', 'Ultimate truth', 'Anime', 2),
('信念', 'Shinnen', 'Belief / Conviction', 'Anime', 2),
('理想', 'Risou', 'Ideal', 'Anime', 3),
('現実', 'Genjitsu', 'Reality', 'Anime', 3),
('矛盾', 'Mujun', 'Contradiction / Paradox', 'Anime', 2),
('混沌', 'Konton', 'Chaos', 'Anime', 2),
('秩序', 'Chitsujo', 'Order / Discipline', 'Anime', 2),
('均衡', 'Kinkou', 'Balance / Equilibrium', 'Anime', 2),
('崩壊', 'Houkai', 'Collapse / Breakdown', 'Anime', 2),

-- ── Seasons / Festivals (季節・祭り) ──────────────────────────────
('花見', 'Hanami', 'Cherry blossom viewing', 'Cultural', 3),
('花火', 'Hanabi', 'Fireworks', 'Cultural', 4),
('夏祭り', 'Natsumatsuri', 'Summer festival', 'Cultural', 3),
('七夕', 'Tanabata', 'Star festival (July 7th)', 'Cultural', 3),
('お正月', 'Oshougatsu', 'New Year', 'Cultural', 4),
('お盆', 'Obon', 'Obon festival / Ancestor memorial', 'Cultural', 3),
('節分', 'Setsubun', 'Bean-throwing ceremony', 'Cultural', 3),
('初詣', 'Hatsumōde', 'First shrine visit of the New Year', 'Cultural', 3),
('浴衣', 'Yukata', 'Summer kimono', 'Cultural', 3),
('縁日', 'Ennichi', 'Festival fair / Street stall festival', 'Cultural', 3),

-- ── Food (食べ物) ──────────────────────────────────────────────────
('弁当', 'Bentou', 'Bento box / Packed lunch', 'Food', 4),
('ラーメン', 'Raamen', 'Ramen', 'Food', 4),
('うどん', 'Udon', 'Udon noodles', 'Food', 4),
('そば', 'Soba', 'Soba noodles', 'Food', 4),
('寿司', 'Sushi', 'Sushi', 'Food', 4),
('天ぷら', 'Tenpura', 'Tempura', 'Food', 4),
('焼肉', 'Yakiniku', 'Grilled meat / Japanese BBQ', 'Food', 4),
('たこ焼き', 'Takoyaki', 'Takoyaki (octopus balls)', 'Food', 4),
('お好み焼き', 'Okonomiyaki', 'Okonomiyaki (savory pancake)', 'Food', 4),
('抹茶', 'Maccha', 'Matcha / Powdered green tea', 'Food', 3),
('おにぎり', 'Onigiri', 'Rice ball', 'Food', 4),
('味噌汁', 'Misoshiru', 'Miso soup', 'Food', 4),
('刺身', 'Sashimi', 'Sashimi (sliced raw fish)', 'Food', 3),

-- ── Nature (自然) ──────────────────────────────────────────────────
('嵐', 'Arashi', 'Storm', 'Anime', 4),
('稲妻', 'Inazuma', 'Lightning bolt', 'Anime', 3),
('竜巻', 'Tatsumaki', 'Tornado / Whirlwind', 'Anime', 3),
('大地', 'Daichi', 'The earth / Ground / Land', 'Anime', 3),
('峡谷', 'Kyoukoku', 'Canyon / Gorge', 'Anime', 2),
('断崖', 'Dangai', 'Cliff / Precipice', 'Anime', 2),
('森', 'Mori', 'Forest', 'Anime', 4),
('洞窟', 'Doukutsu', 'Cave / Cavern', 'Anime', 3),

-- ── Miscellaneous Anime Vocab ─────────────────────────────────────
('主人公', 'Shujinkou', 'Main character / Protagonist', 'Anime', 3),
('悪役', 'Akuyaku', 'Villain / Antagonist', 'Anime', 3),
('天才', 'Tensai', 'Genius', 'Anime', 3),
('努力', 'Doryoku', 'Effort / Hard work', 'Anime', 3),
('根性', 'Konjou', 'Guts / Grit / Fighting spirit', 'Anime', 3),
('友情', 'Yuujou', 'Friendship / Bond of friendship', 'Anime', 3),
('絆', 'Kizuna', 'Bond / Emotional connection', 'Anime', 3),
('成長', 'Seichou', 'Growth / Personal development', 'Anime', 3),
('自由', 'Jiyuu', 'Freedom / Liberty', 'Anime', 4),
('平和', 'Heiwa', 'Peace', 'Anime', 4),
('世界征服', 'Sekai seifuku', 'World domination', 'Anime', 3),
('復活', 'Fukkatsu', 'Revival / Return / Comeback', 'Anime', 3),
('帰還', 'Kikan', 'Return / Homecoming (from battle)', 'Anime', 2),
('探索', 'Tansaku', 'Exploration / Search', 'Anime', 3),
('発見', 'Hakken', 'Discovery', 'Anime', 3),
('証拠', 'Shouko', 'Evidence / Proof', 'Anime', 3),
('解決', 'Kaiketsu', 'Resolution / Solving a problem', 'Anime', 3),
('変装', 'Hensou', 'Disguise', 'Anime', 3),
('偽物', 'Nisemono', 'Fake / Impostor', 'Anime', 3),
('本物', 'Honmono', 'Real / Genuine', 'Anime', 3),
('最終決戦', 'Saishuu kessen', 'Final battle', 'Anime', 2),
('伏線', 'Fukusen', 'Foreshadowing / Plot setup', 'Anime', 1),
('どんでん返し', 'Dondengaeshi', 'Plot twist / Dramatic reversal', 'Anime', 2),
('修羅場', 'Shuraba', 'Scene of carnage / Intense confrontation', 'Anime', 2),
('熱血', 'Nekketsu', 'Hot-blooded / Passionate spirit', 'Anime', 2),
('王道', 'Oudou', 'The orthodox way / Classic trope', 'Anime', 2),
('バカ', 'Baka', 'Idiot / Stupid', 'Anime', 4),
('うん', 'Un', 'Yeah / Uh-huh (casual)', 'Anime', 5),
('だから', 'Dakara', 'That''s why / Therefore', 'Anime', 4),
('でも', 'Demo', 'But / However', 'Anime', 4),
('なるほど', 'Naruhodo', 'I see / That makes sense', 'Anime', 3),
('すごい', 'Sugoi', 'Amazing / Incredible', 'Anime', 4),
('やばい', 'Yabai', 'Crazy / Dangerous / Awesome (slang)', 'Anime', 4),
('かわいい', 'Kawaii', 'Cute', 'Anime', 4),
('かっこいい', 'Kakkoii', 'Cool / Stylish', 'Anime', 4),
('最高', 'Saikou', 'The best / Awesome', 'Anime', 3),
('大丈夫', 'Daijoubu', 'It''s okay / Are you alright?', 'Anime', 4),
('気をつけて', 'Ki wo tsukete', 'Be careful / Take care', 'Anime', 4),
('頑張れ', 'Ganbare', 'Do your best! / You can do it!', 'Anime', 4),
('仕方ない', 'Shikata nai', 'It can''t be helped / Nothing to do about it', 'Anime', 3),
('どうせ', 'Douse', 'Anyway / Which way / At any rate', 'Anime', 3),
('きっと', 'Kitto', 'Surely / Certainly / I''m sure', 'Anime', 3),
('ついに', 'Tsuini', 'Finally / At last', 'Anime', 3),
('もしかして', 'Moshikashite', 'Could it be? / By any chance?', 'Anime', 3),
('だろう', 'Darou', 'Probably / Right? / I suppose', 'Anime', 3),
('当然', 'Touzen', 'Of course / Naturally / Obviously', 'Anime', 3),
('鬼畜', 'Kichiku', 'Fiend / Merciless person', 'Anime', 1),

-- ── Additional vocabulary ─────────────────────────────────────────
('運動神経', 'Undou shinkei', 'Athletic ability / Motor nerves', 'School', 3),
('天敵', 'Tenteki', 'Natural enemy / Nemesis', 'Anime', 2),
('刺客', 'Shikaku', 'Assassin', 'Anime', 2),
('暗殺', 'Ansatsu', 'Assassination', 'Anime', 2),
('拷問', 'Goumon', 'Torture', 'Anime', 1),
('尋問', 'Jinmon', 'Interrogation', 'Anime', 2),
('捜索', 'Sousaku', 'Search / Hunt', 'Anime', 3),
('追跡', 'Tsuiseki', 'Pursuit / Chase', 'Anime', 2),
('逃走', 'Tousou', 'Escape / Flight', 'Anime', 2),
('潜入', 'Sennyuu', 'Infiltration / Sneaking in', 'Anime', 2),
('偵察', 'Teisatsu', 'Reconnaissance / Scouting', 'Anime', 2),
('護衛', 'Goei', 'Bodyguard / Escort', 'Anime', 2),
('人質', 'Hitojichi', 'Hostage', 'Anime', 2),
('脱出', 'Dasshutsu', 'Escape / Break out', 'Anime', 3),
('救出', 'Kyuushutsu', 'Rescue', 'Anime', 3),
('決意', 'Ketsui', 'Determination / Resolution', 'Anime', 3),
('覚悟を決める', 'Kakugo wo kimeru', 'To make up one''s mind / Steel oneself', 'Anime', 2),
('立ち向かう', 'Tachimukau', 'To face / Confront', 'Anime', 2),
('乗り越える', 'Norikoeru', 'To overcome / Get through', 'Anime', 3),
('諦める', 'Akirameru', 'To give up', 'Anime', 3),
('信じる', 'Shinjiru', 'To believe / Trust', 'Anime', 4),
('疑う', 'Utagau', 'To doubt / Suspect', 'Anime', 3),
('守り抜く', 'Mamorinuku', 'To protect until the end', 'Anime', 2),
('生き残る', 'Ikinokoru', 'To survive / Remain alive', 'Anime', 3),
('犠牲になる', 'Gisei ni naru', 'To become a sacrifice / Give one''s life', 'Anime', 2),
('かばう', 'Kabau', 'To shield / Protect someone', 'Anime', 3),
('見捨てる', 'Misuteru', 'To abandon / Leave behind', 'Anime', 2),
('後を追う', 'Ato wo ou', 'To follow after / Give chase', 'Anime', 2),
('戦い続ける', 'Tatakaitsudzukeru', 'To keep fighting', 'Anime', 2),
('立ち上がる', 'Tachiagaru', 'To stand up / Rise again', 'Anime', 3),
('目覚める', 'Mezameru', 'To awaken / Wake up (power)', 'Anime', 3),
('解き放つ', 'Tokihanatsu', 'To unleash / Set free', 'Anime', 2),
('挑む', 'Idomu', 'To challenge / Take on', 'Anime', 2),
('圧倒する', 'Attou suru', 'To overwhelm / Overpower', 'Anime', 2),
('打ち破る', 'Uchiyaburu', 'To break through / Defeat', 'Anime', 2),
('見極める', 'Mikiwameru', 'To ascertain / See through', 'Anime', 2),
('力を合わせる', 'Chikara wo awaseru', 'To join forces / Combine strength', 'Anime', 3),
('共闘', 'Kyoutou', 'Fighting together / Joint battle', 'Anime', 2),
('脅威', 'Kyoui', 'Threat / Menace', 'Anime', 2),
('強敵', 'Kyouteki', 'Powerful enemy / Formidable foe', 'Anime', 2),
('宿敵', 'Shukuteki', 'Arch-enemy / Sworn enemy', 'Anime', 2),
('死闘', 'Shitou', 'Fight to the death / Deadly struggle', 'Battle', 2),
('激闘', 'Gekitou', 'Fierce battle / Hard-fought fight', 'Battle', 2),
('血戦', 'Kessen', 'Bloody battle', 'Battle', 1),
('孤軍奮闘', 'Kogun funtou', 'Fighting alone / Single-handed struggle', 'Battle', 1),
('勝負', 'Shoubu', 'Match / Contest / Showdown', 'Anime', 4),
('決着', 'Ketchaku', 'Settlement / Conclusion of a fight', 'Anime', 2),
('敗北', 'Haiboku', 'Defeat / Loss', 'Anime', 3),
('雪辱', 'Sekijoku', 'Revenge for a loss / Vindication', 'Anime', 1),
('不屈', 'Fukutsu', 'Indomitable / Unyielding spirit', 'Anime', 2),
('執着', 'Shichaku', 'Attachment / Fixation / Persistence', 'Anime', 2),
('無謀', 'Mubou', 'Reckless / Rash', 'Anime', 2),
('策略', 'Sakuryaku', 'Strategy / Scheme / Trick', 'Anime', 2),
('罠にはまる', 'Wana ni hamaru', 'To fall into a trap', 'Anime', 2),
('逆境', 'Gyakkyou', 'Adversity / Difficult situation', 'Anime', 2),
('土壇場', 'Dotanba', 'Last moment / At the brink', 'Anime', 2),
('神業', 'Kamiwaza', 'Godlike skill / Superhuman feat', 'Anime', 2),
('伝家の宝刀', 'Denka no houtou', 'Trump card / Secret weapon (idiom)', 'Anime', 1),
('一騎当千', 'Ikki tosen', 'Worth a thousand soldiers / Unmatched fighter', 'Anime', 1),
('不撓不屈', 'Futou fukutsu', 'Dauntless perseverance / Never giving in', 'Anime', 1),
('七転八起', 'Shichi ten hakki', 'Fall seven times, rise eight / Never give up', 'Anime', 1),
('一念発起', 'Ichinen hokki', 'Resolving firmly / Making a strong decision', 'Anime', 1);

