-- Migration 015: Comprehensive anime vocabulary expansion (~160 new words)
-- ON CONFLICT DO NOTHING handles any accidental duplicates safely

INSERT INTO content_vocabulary (japanese, reading, english, category, jlpt_level) VALUES

-- ── RPG / Fantasy Systems (RPGシステム) ───────────────────────────
('詠唱', 'Eichou', 'Incantation / Spell chanting / Casting', 'Fantasy', 2),
('ステータス', 'Suteetasu', 'Status / Stats / Parameters', 'Fantasy', 4),
('クエスト', 'Kuesuto', 'Quest / Mission', 'Fantasy', 4),
('神託', 'Shintaku', 'Oracle / Divine message / Prophecy', 'Fantasy', 2),
('秘術', 'Hijutsu', 'Secret art / Hidden technique', 'Fantasy', 2),
('剣術', 'Kenjutsu', 'Swordsmanship / Sword technique', 'Fantasy', 2),
('錬金術', 'Renkinjutsu', 'Alchemy / Alchemical art', 'Fantasy', 2),
('禁術', 'Kinjutsu', 'Forbidden technique / Black arts', 'Fantasy', 2),
('宝具', 'Hougu', 'Noble Phantasm / Sacred treasure', 'Fantasy', 2),
('遺跡', 'Iseki', 'Ancient ruins / Ruins', 'Fantasy', 3),
('王都', 'Outo', 'Royal capital / Capital city', 'Fantasy', 2),
('学園', 'Gakuen', 'Academy / School campus', 'School', 3),
('儀式', 'Gishiki', 'Ritual / Ceremony', 'Fantasy', 3),
('召喚陣', 'Shoukanjin', 'Summoning circle / Summoning array', 'Fantasy', 2),
('転移陣', 'Ten''ijin', 'Teleportation circle / Warp array', 'Fantasy', 2),
('マナ', 'Mana', 'Mana / Magic energy', 'Fantasy', 4),
('エーテル', 'Eeteru', 'Ether / Aether / Ethereal energy', 'Fantasy', 3),
('魔素', 'Maso', 'Magic particle / Magical element', 'Fantasy', 2),
('魔獣', 'Majuu', 'Magical beast / Monster creature', 'Fantasy', 2),
('ラスボス', 'Rasubosu', 'Final boss / Last boss', 'Fantasy', 4),

-- ── Weapons (武器・武具) ───────────────────────────────────────────
('聖槍', 'Seisou', 'Holy spear / Sacred lance', 'Battle', 2),
('双剣', 'Soukeen', 'Dual swords / Twin blades', 'Battle', 2),
('大剣', 'Ootachi', 'Greatsword / Large sword', 'Battle', 3),
('短剣', 'Tanken', 'Dagger / Short sword', 'Battle', 3),
('鎌', 'Kama', 'Scythe / Sickle', 'Battle', 3),
('紋章', 'Monshou', 'Crest / Emblem / Coat of arms', 'Fantasy', 2),
('烙印', 'Rakuin', 'Brand / Stigma / Cursed mark', 'Fantasy', 2),

-- ── Aura / Energy (気・オーラ) ─────────────────────────────────────
('闘気', 'Touki', 'Battle aura / Fighting spirit energy', 'Anime', 2),
('覇気', 'Haki', 'Domineering spirit / Conqueror''s aura', 'Anime', 2),
('邪気', 'Jaki', 'Evil energy / Malice aura', 'Anime', 2),
('妖気', 'Youki', 'Supernatural energy / Demonic aura', 'Anime', 2),
('気配', 'Kehai', 'Presence / Sense of someone nearby', 'Anime', 3),
('殺気', 'Sakki', 'Killing intent / Murderous aura', 'Battle', 2),
('威圧', 'Iiatsu', 'Intimidation / Menacing pressure', 'Battle', 2),
('暴走', 'Bousou', 'Rampage / Going berserk / Out of control', 'Anime', 2),

-- ── Battle / Combat (戦闘) ────────────────────────────────────────
('戦闘', 'Sentou', 'Combat / Battle / Fighting', 'Battle', 3),
('戦い', 'Tatakai', 'Fight / Battle / Struggle', 'Battle', 4),
('決戦', 'Kessen', 'Decisive battle / Showdown', 'Battle', 2),
('激突', 'Gekitotsu', 'Clash / Collision / Fierce impact', 'Battle', 2),
('対峙', 'Taiji', 'Standoff / Facing off / Confrontation', 'Battle', 2),
('対決', 'Taiketsu', 'Showdown / Head-to-head / Duel', 'Battle', 3),
('逆襲', 'Gyakushuu', 'Counterattack / Strike back', 'Battle', 2),
('反乱', 'Hanran', 'Rebellion / Revolt / Uprising', 'Battle', 2),
('停戦', 'Taisen', 'Ceasefire / Truce / Armistice', 'Battle', 2),
('宣戦布告', 'Sensen fukoku', 'Declaration of war', 'Battle', 2),
('一騎打ち', 'Ikkiuchi', 'One-on-one duel / Single combat', 'Battle', 2),
('総力戦', 'Souryokusen', 'All-out war / Total war', 'Battle', 2),
('激戦', 'Gekisen', 'Fierce battle / Hard-fought fight', 'Battle', 2),
('前衛', 'Zen''ei', 'Vanguard / Front line guard', 'Battle', 2),
('後衛', 'Kouei', 'Rear guard / Back line', 'Battle', 2),
('支援', 'Shien', 'Support / Backup / Aid', 'Battle', 3),
('援護', 'Engo', 'Cover fire / Combat support', 'Battle', 2),
('重傷', 'Juushou', 'Serious injury / Severe wound', 'Battle', 3),
('軽傷', 'Keishou', 'Minor injury / Light wound', 'Battle', 3),
('致命傷', 'Chimei shou', 'Fatal wound / Lethal injury', 'Battle', 2),
('生還', 'Seikan', 'Safe return / Survival from danger', 'Battle', 2),
('気絶', 'Kizetsu', 'Fainting / Losing consciousness', 'Battle', 3),
('勲章', 'Kunshou', 'Medal / Military decoration', 'Battle', 3),
('攻撃', 'Kougeki', 'Attack / Offensive / Strike', 'Battle', 3),
('防御', 'Bougyo', 'Defense / Defensive stance', 'Battle', 3),
('回避', 'Kaihi', 'Evasion / Dodge / Avoidance', 'Battle', 3),
('剣技', 'Kengi', 'Sword technique / Sword skill', 'Battle', 2),
('格闘', 'Kakutou', 'Hand-to-hand combat / Grappling', 'Battle', 3),
('陣形', 'Jinkei', 'Battle formation / Tactical formation', 'Battle', 2),
('四天王', 'Shitennō', 'Four Heavenly Kings / Top four elites', 'Anime', 2),
('傭兵', 'Youhei', 'Mercenary / Hired soldier', 'Battle', 2),
('好敵手', 'Koutekishu', 'Worthy rival / Well-matched opponent', 'Anime', 2),
('弓兵', 'Kyuuhei', 'Archer / Bowman', 'Battle', 2),
('槍兵', 'Souhei', 'Spearman / Lancer', 'Battle', 2),

-- ── Roles / World (役職・世界) ─────────────────────────────────────
('王女', 'Oujo', 'Princess / King''s daughter', 'Fantasy', 3),
('聖騎士', 'Seikishi', 'Holy knight / Paladin', 'Fantasy', 2),
('団長', 'Danchou', 'Commander / Group leader / Guild master', 'Anime', 3),
('宰相', 'Saishou', 'Prime minister / Chancellor / Grand vizier', 'Fantasy', 2),
('教会', 'Kyoukai', 'Church / Cathedral', 'Fantasy', 4),
('守護者', 'Shugosha', 'Guardian / Protector', 'Anime', 2),
('支配者', 'Shihaisha', 'Ruler / Dominator / Overlord', 'Anime', 2),
('魔導士', 'Madoushi', 'Mage / Magic user', 'Fantasy', 2),
('狙撃手', 'Sogekishu', 'Sniper / Sharpshooter', 'Battle', 2),
('暗殺者', 'Ansatsusha', 'Assassin', 'Battle', 2),
('眷属', 'Kenzoku', 'Minions / Kin / Loyal followers', 'Fantasy', 1),
('王様', 'Ousama', 'King / Your Majesty', 'Fantasy', 4),
('剣豪', 'Kengo', 'Master swordsman / Sword saint', 'Fantasy', 2),
('魔法使い', 'Mahoutsuka', 'Wizard / Witch / Magic user', 'Fantasy', 4),
('魔術師', 'Majutsushi', 'Sorcerer / Magician / Illusionist', 'Fantasy', 2),
('僧侶', 'Souryo', 'Monk / Buddhist priest / Cleric', 'Fantasy', 3),
('狩人', 'Kariudo', 'Hunter / Ranger', 'Fantasy', 3),
('召喚士', 'Shoukanshi', 'Summoner', 'Fantasy', 2),
('治療師', 'Chiryoushi', 'Healer / Medic', 'Fantasy', 2),
('商人', 'Shounin', 'Merchant / Trader', 'Fantasy', 4),
('鍛冶屋', 'Kajiya', 'Blacksmith / Armorer', 'Fantasy', 3),
('旅人', 'Tabibito', 'Traveler / Wanderer', 'Fantasy', 4),
('学者', 'Gakusha', 'Scholar / Researcher', 'Fantasy', 4),
('預言者', 'Yogensha', 'Prophet / Seer', 'Fantasy', 2),
('長老', 'Chourou', 'Elder / Wise elder', 'Fantasy', 3),
('村長', 'Sonchou', 'Village chief / Mayor', 'Fantasy', 4),
('領主', 'Ryoushu', 'Lord / Feudal lord / Domain ruler', 'Fantasy', 2),
('貴族', 'Kizoku', 'Nobleman / Aristocrat / Noble', 'Fantasy', 3),
('平民', 'Heimin', 'Commoner / Ordinary citizen', 'Fantasy', 3),
('執事', 'Shitsuji', 'Butler / Steward', 'Fantasy', 3),
('メイド', 'Meido', 'Maid / Maidservant', 'Anime', 4),
('船長', 'Senchou', 'Ship captain / Captain', 'Anime', 3),
('兵士', 'Heishi', 'Soldier / Troops', 'Battle', 4),
('衛兵', 'Eihei', 'Palace guard / Sentry', 'Fantasy', 2),

-- ── Narrative / Plot (ストーリー展開) ─────────────────────────────
('序章', 'Joshou', 'Prologue / Opening chapter', 'Anime', 2),
('開幕', 'Kaimaku', 'Opening / The curtain rises / It begins!', 'Anime', 2),
('終幕', 'Shuumaku', 'Finale / Curtain falls / The end', 'Anime', 2),
('降臨', 'Kourin', 'Descent / Divine appearance / A god arrives!', 'Fantasy', 2),
('顕現', 'Kengen', 'Manifestation / Revelation / Appearing', 'Fantasy', 1),
('消滅', 'Shoumetsu', 'Disappearance / Annihilation / Erasure', 'Anime', 2),
('再臨', 'Sairin', 'Second coming / Return of a legend', 'Anime', 2),
('瞬間移動', 'Shunkan idou', 'Teleportation / Instant movement', 'Fantasy', 2),
('幻術', 'Genjutsu', 'Illusion technique / Genjutsu', 'Fantasy', 2),
('催眠', 'Saimin', 'Hypnosis / Hypnotism', 'Anime', 2),
('洗脳', 'Sennou', 'Brainwashing / Mind control', 'Anime', 2),
('解呪', 'Kaijuu', 'Dispelling a curse / Curse removal', 'Fantasy', 2),
('呪詛', 'Juso', 'Curse / Hex / Malediction', 'Fantasy', 1),
('啓示', 'Keiji', 'Revelation / Divine revelation', 'Fantasy', 2),
('神罰', 'Shimbatsu', 'Divine punishment / Wrath of God', 'Fantasy', 2),
('審判', 'Shinpan', 'Judgment / Trial / Final Judgment', 'Fantasy', 2),
('救世主', 'Kyuuseishu', 'Savior / Messiah / Chosen One', 'Anime', 2),
('生贄', 'Ikenie', 'Sacrifice / Offering / Scapegoat', 'Fantasy', 2),
('真相', 'Shinsou', 'The truth / The whole story / What really happened', 'Anime', 3),
('因果', 'Inga', 'Karma / Cause and effect / Fate''s irony', 'Anime', 2),
('虚無', 'Kyomu', 'Nothingness / Void / Nihility', 'Anime', 2),
('破滅', 'Hametsu', 'Ruin / Destruction / Downfall', 'Anime', 2),
('終末', 'Shuumatsu', 'Apocalypse / End of the world / Ragnarok', 'Anime', 2),
('新世界', 'Shinsekai', 'New world / New order', 'Anime', 3),
('プロローグ', 'Puroogu', 'Prologue', 'Anime', 3),
('エピローグ', 'Epiroogu', 'Epilogue', 'Anime', 3),
('亡国', 'Boukoku', 'Fallen kingdom / Ruined nation', 'Fantasy', 2),
('建国', 'Kenkoku', 'Founding of a nation', 'Fantasy', 2),
('因縁', 'Innen', 'Deep fate / Karma / Destined ties', 'Anime', 2),
('黒幕', 'Kuromaku', 'Mastermind / Puppet master / Big bad', 'Anime', 2),
('神話', 'Shinwa', 'Mythology / Myth / Legend of the gods', 'Fantasy', 3),
('時空', 'Jikuu', 'Space-time / Dimension of time', 'Fantasy', 2),
('次元', 'Jigen', 'Dimension / Plane of existence', 'Fantasy', 2),
('世界線', 'Sekaisen', 'World line / Timeline / Parallel world path', 'Fantasy', 2),
('黒歴史', 'Kurorekishi', 'Dark history / Cringe-worthy past / Eighth-grader moment', 'Anime', 3),

-- ── School Life (学校生活) ─────────────────────────────────────────
('生徒会長', 'Seitokaichou', 'Student council president', 'School', 3),
('クラスメイト', 'Kurasu meeto', 'Classmate', 'School', 4),
('担任', 'Tan''nin', 'Homeroom teacher / Class teacher', 'School', 3),
('教室', 'Kyoushitsu', 'Classroom', 'School', 4),
('廊下', 'Rouka', 'Hallway / Corridor', 'School', 3),
('寮', 'Ryou', 'Dormitory / School dorm', 'School', 3),
('赤点', 'Akaten', 'Failing grade / Red mark', 'School', 3),
('補習', 'Hoshuu', 'Remedial class / Make-up lesson', 'School', 3),
('卒業式', 'Sotsugyoushiki', 'Graduation ceremony', 'School', 3),
('入学式', 'Nyuugakushiki', 'School entrance ceremony', 'School', 3),
('温泉', 'Onsen', 'Hot spring / Hot spring bath', 'Cultural', 4),
('肝試し', 'Kimodameshi', 'Test of courage / Haunted spot ordeal', 'Cultural', 3),
('合宿', 'Gasshuku', 'Training camp / Group lodging / Boot camp', 'School', 3),
('秀才', 'Shuusai', 'Brilliant student / Talented person', 'School', 2),
('落ちこぼれ', 'Ochikobore', 'Dropout / Underachiever / Failure', 'School', 2),
('優等生', 'Yuutosei', 'Honor student / Top student / Model student', 'School', 2),
('劣等生', 'Retsutosei', 'Poor student / Bottom of the class', 'School', 2),
('問題児', 'Mondaiji', 'Problem child / Troublemaker', 'School', 3),
('留学生', 'Ryuugakusei', 'Exchange student / Student studying abroad', 'School', 3),

-- ── Memories / Connection (思い出・絆) ────────────────────────────
('思い出', 'Omoide', 'Memory / Memories / Recollection', 'Anime', 3),
('仲直り', 'Nakanaroi', 'Making up / Reconciliation / Patching things up', 'Romance', 3),
('愛情', 'Aijou', 'Affection / Deep love / Loving feelings', 'Romance', 3),

-- ── Emotions / Character (感情・性格) ─────────────────────────────
('勇気', 'Yuuki', 'Courage / Bravery', 'Emotions', 4),
('信頼', 'Shinrai', 'Trust / Reliance / Confidence in someone', 'Emotions', 3),
('幸福', 'Koufuku', 'Happiness / Bliss', 'Emotions', 3),
('喜び', 'Yorokobi', 'Joy / Delight / Happiness', 'Emotions', 3),
('怒り', 'Ikari', 'Anger / Rage / Wrath', 'Emotions', 3),
('不安', 'Fuan', 'Anxiety / Worry / Unease', 'Emotions', 3),
('冷静', 'Reisei', 'Calm / Cool-headed / Composed', 'Emotions', 3),
('動揺', 'Douyou', 'Upset / Shaken / Flustered', 'Emotions', 2),
('情熱', 'Jounetsu', 'Passion / Fervor / Burning desire', 'Emotions', 2),
('意志', 'Ishi', 'Will / Willpower / Determination', 'Emotions', 3),
('野望', 'Yabou', 'Ambition / Grand aspiration', 'Emotions', 2),
('欲望', 'Yokubou', 'Desire / Craving / Greed', 'Emotions', 2),
('謙虚', 'Kenkyo', 'Humility / Modesty', 'Emotions', 2),
('傲慢', 'Gouman', 'Arrogance / Haughtiness / Pride', 'Emotions', 2),
('悪意', 'Akui', 'Malice / Evil intent / Ill will', 'Emotions', 2),
('善意', 'Zen''i', 'Goodwill / Good intentions / Benevolence', 'Emotions', 2),
('良心', 'Ryoushin', 'Conscience / Moral sense', 'Emotions', 3),
('忠誠', 'Chuusei', 'Loyalty / Allegiance / Fidelity', 'Emotions', 2),
('誠実', 'Seijitsu', 'Sincerity / Integrity / Honesty', 'Emotions', 2),
('無邪気', 'Mujaki', 'Innocent / Guileless / Childlike purity', 'Emotions', 2),
('臆病', 'Okubyou', 'Cowardly / Timid / Fearful', 'Emotions', 2),
('勇敢', 'Yuukan', 'Brave / Courageous / Valiant', 'Emotions', 2),
('大胆', 'Daitan', 'Bold / Daring / Audacious', 'Emotions', 2),
('冷酷', 'Reikoku', 'Cold-hearted / Ruthless / Merciless', 'Emotions', 2),
('温厚', 'Onkou', 'Gentle / Mild-mannered / Warm-hearted', 'Emotions', 2),
('親切', 'Shinsetsu', 'Kind / Kindness / Being helpful', 'Emotions', 4),
('厳格', 'Genkaku', 'Strict / Stern / Rigid', 'Emotions', 2),
('寛容', 'Kan''you', 'Tolerant / Forgiving / Magnanimous', 'Emotions', 2),
('忍耐', 'Nintai', 'Patience / Endurance / Perseverance', 'Emotions', 2),
('我慢', 'Gaman', 'Patience / Self-control / Holding back', 'Emotions', 3),
('自信', 'Jishin', 'Self-confidence / Confidence', 'Emotions', 3),
('尊敬', 'Sonkei', 'Respect / Admiration / Reverence', 'Emotions', 3),
('憧れ', 'Akogare', 'Longing / Admiration / Aspiration', 'Emotions', 3),
('感謝', 'Kansha', 'Gratitude / Thankfulness', 'Emotions', 3),
('孤立', 'Koritsu', 'Isolation / Alienation / Being alone', 'Emotions', 3),
('栄光', 'Eikou', 'Glory / Honor / Triumph', 'Emotions', 2),
('思いやり', 'Omoiyari', 'Compassion / Consideration / Empathy', 'Emotions', 2),
('慈悲', 'Jihi', 'Mercy / Compassion / Benevolence', 'Emotions', 2)

ON CONFLICT (japanese) DO NOTHING;
