-- Migration 016: Anime vocabulary part 2 - locations, items, creatures, military, family, forms (~220 words)

INSERT INTO content_vocabulary (japanese, reading, english, category, jlpt_level) VALUES

-- ── Locations / World Map (場所・地形) ─────────────────────────────
('城下町', 'Joukamachi', 'Castle town / Town below the castle', 'Fantasy', 3),
('宮殿', 'Kyuuden', 'Palace / Royal palace', 'Fantasy', 3),
('王宮', 'Oukyuu', 'Royal palace / Imperial court', 'Fantasy', 2),
('村', 'Mura', 'Village', 'Fantasy', 4),
('集落', 'Shuuraku', 'Settlement / Hamlet', 'Fantasy', 3),
('都', 'Miyako', 'Capital city / Metropolis', 'Fantasy', 3),
('首都', 'Shuto', 'Capital / National capital', 'Fantasy', 3),
('港町', 'Minatomachi', 'Port town / Harbor city', 'Fantasy', 3),
('草原', 'Sougen', 'Grassland / Prairie / Meadow', 'Fantasy', 3),
('平原', 'Heigen', 'Plains / Flatlands', 'Fantasy', 3),
('丘', 'Oka', 'Hill / Hilltop', 'Fantasy', 4),
('峠', 'Touge', 'Mountain pass / Summit pass', 'Fantasy', 3),
('谷', 'Tani', 'Valley / Ravine', 'Fantasy', 4),
('崖', 'Gake', 'Cliff / Precipice', 'Fantasy', 3),
('地下道', 'Chikadou', 'Underground tunnel / Underpass', 'Fantasy', 3),
('神社', 'Jinja', 'Shinto shrine', 'Cultural', 4),
('寺', 'Tera', 'Temple / Buddhist temple', 'Cultural', 4),
('聖堂', 'Seidou', 'Sanctuary / Cathedral / Holy hall', 'Fantasy', 2),
('塔', 'Tou', 'Tower / Spire', 'Fantasy', 4),
('灯台', 'Toudai', 'Lighthouse', 'Fantasy', 3),
('砦', 'Toride', 'Fort / Fortress / Stronghold', 'Battle', 3),
('要塞', 'Yousai', 'Fortress / Stronghold / Citadel', 'Battle', 2),
('城壁', 'Jouhetsu', 'Castle wall / Rampart / Battlement', 'Battle', 2),
('広場', 'Hiroba', 'Plaza / Town square / Open space', 'Fantasy', 4),
('市場', 'Ichiba', 'Market / Marketplace / Bazaar', 'Fantasy', 4),
('宿屋', 'Yadoya', 'Inn / Lodge / Tavern', 'Fantasy', 3),
('酒場', 'Sakaba', 'Tavern / Bar / Pub', 'Fantasy', 3),
('書庫', 'Shoko', 'Archive / Book vault / Library vault', 'Fantasy', 2),
('工房', 'Koubou', 'Workshop / Atelier / Studio', 'Fantasy', 3),
('鍛冶場', 'Kajiba', 'Forge / Smithy / Blacksmith shop', 'Fantasy', 3),
('禁域', 'Kin''iki', 'Forbidden zone / Restricted area', 'Fantasy', 2),
('魔境', 'Makyou', 'Demon territory / Cursed land', 'Fantasy', 2),
('沼地', 'Numachi', 'Swamp / Bog / Marshland', 'Fantasy', 3),
('湖', 'Mizuumi', 'Lake', 'Fantasy', 4),
('滝', 'Taki', 'Waterfall', 'Fantasy', 4),
('浜辺', 'Hamabe', 'Beach / Shoreline', 'Fantasy', 3),
('島', 'Shima', 'Island', 'Fantasy', 4),
('無人島', 'Mujintou', 'Uninhabited island / Desert island', 'Fantasy', 3),
('火山', 'Kazan', 'Volcano', 'Fantasy', 3),
('雪原', 'Yukihara', 'Snowfield / Snow plain', 'Fantasy', 3),
('氷原', 'Kouhara', 'Ice field / Frozen wasteland', 'Fantasy', 2),
('砂漠', 'Sabaku', 'Desert', 'Fantasy', 3),
('荒野', 'Kouya', 'Wasteland / Wilderness / Barren land', 'Fantasy', 3),
('密林', 'Mitsurin', 'Dense jungle / Thick forest', 'Fantasy', 2),
('雲海', 'Unkai', 'Sea of clouds / Cloud ocean', 'Fantasy', 2),
('炭鉱', 'Tankou', 'Coal mine / Mine', 'Fantasy', 3),
('迷宮', 'Meikyuu', 'Labyrinth / Maze / Dungeon maze', 'Fantasy', 3),
('屋上', 'Okujou', 'Rooftop / School rooftop', 'School', 3),
('体育館', 'Taiikukan', 'Gymnasium / Gym', 'School', 4),
('保健室', 'Hokenshitsu', 'Nurse''s office / Health room', 'School', 3),

-- ── Items / Equipment (アイテム・装備) ────────────────────────────
('杖', 'Tsue', 'Staff / Wand / Magic staff', 'Fantasy', 4),
('指輪', 'Yubiwa', 'Ring / Magic ring', 'Fantasy', 4),
('首飾り', 'Kubikazari', 'Necklace / Pendant / Choker', 'Fantasy', 3),
('王冠', 'Oucan', 'Crown / Royal crown', 'Fantasy', 3),
('ローブ', 'Roobu', 'Robe / Wizard robe', 'Fantasy', 4),
('マント', 'Manto', 'Cloak / Mantle / Cape', 'Fantasy', 4),
('巻物', 'Makimono', 'Scroll / Magic scroll', 'Fantasy', 3),
('護符', 'Gofu', 'Protective charm / Talisman', 'Fantasy', 2),
('お守り', 'Omamori', 'Good luck charm / Amulet', 'Cultural', 4),
('宝石', 'Houseki', 'Gemstone / Jewel', 'Fantasy', 3),
('水晶', 'Suishou', 'Crystal / Crystal ball', 'Fantasy', 3),
('遺物', 'Ibutsu', 'Relic / Ancient artifact', 'Fantasy', 2),
('魔導書', 'Madousho', 'Grimoire / Magic tome / Spellbook', 'Fantasy', 2),
('古文書', 'Komonjo', 'Ancient document / Old manuscript', 'Fantasy', 2),

-- ── Creatures / Beings (生物・種族) ───────────────────────────────
('神獣', 'Shinjuu', 'Divine beast / Sacred creature', 'Fantasy', 2),
('幻獣', 'Genjuu', 'Mythical creature / Phantom beast', 'Fantasy', 2),
('聖獣', 'Seijuu', 'Sacred beast / Holy creature', 'Fantasy', 2),
('飛竜', 'Hiryuu', 'Wyvern / Flying dragon', 'Fantasy', 2),
('不死鳥', 'Fushichou', 'Phoenix / Immortal firebird', 'Fantasy', 2),
('人魚', 'Ningyo', 'Mermaid / Merman', 'Fantasy', 3),
('人狼', 'Jinrou', 'Werewolf', 'Fantasy', 2),
('悪霊', 'Akuryou', 'Evil spirit / Malevolent ghost', 'Supernatural', 2),
('霊魂', 'Reikon', 'Soul / Spirit / Departed soul', 'Supernatural', 2),
('巨人', 'Kyojin', 'Giant / Titan', 'Fantasy', 3),
('女神', 'Megami', 'Goddess', 'Fantasy', 3),

-- ── Battle / Combat II (戦闘Ⅱ) ────────────────────────────────────
('殲滅', 'Senmetsu', 'Annihilation / Total extermination', 'Battle', 2),
('制圧', 'Seiatsu', 'Suppression / Domination / Takeover', 'Battle', 2),
('鎮圧', 'Chin''atsu', 'Quelling / Suppression / Crushing a revolt', 'Battle', 2),
('応戦', 'Ousen', 'Fighting back / Returning fire', 'Battle', 2),
('開戦', 'Kaisen', 'Start of war / Outbreak of battle', 'Battle', 2),
('抵抗', 'Teikou', 'Resistance / Opposition / Fighting back', 'Battle', 3),
('白兵戦', 'Hakuhei sen', 'Melee combat / Hand-to-hand fighting', 'Battle', 2),
('接近戦', 'Sekkin sen', 'Close-range combat / Close quarters', 'Battle', 2),
('遠距離攻撃', 'Enkyori kougeki', 'Ranged attack / Long-distance strike', 'Battle', 2),
('射撃', 'Shageki', 'Shooting / Gunfire', 'Battle', 3),
('刺突', 'Shitotsu', 'Thrust attack / Stabbing lunge', 'Battle', 2),
('打撃', 'Dageki', 'Strike / Impact / Blunt blow', 'Battle', 3),
('防壁', 'Bouheki', 'Defensive wall / Shield wall / Barrier', 'Battle', 2),
('戦斧', 'Senpu', 'War axe / Battle axe', 'Battle', 2),
('鎖', 'Kusari', 'Chain / Iron chain', 'Battle', 3),
('鞭', 'Muchi', 'Whip / Lash', 'Battle', 3),
('棍棒', 'Konbou', 'Club / Cudgel / Bludgeon', 'Battle', 3),
('兜', 'Kabuto', 'Helmet / Battle helm / Samurai helmet', 'Battle', 3),
('凱旋', 'Gaisen', 'Triumphal return / Victorious homecoming', 'Battle', 2),
('渾身', 'Konshin', 'With all one''s strength / Full-body effort', 'Battle', 2),
('索敵', 'Sakuteki', 'Searching for enemies / Target acquisition', 'Battle', 2),
('最終形態', 'Saishuu keitai', 'Final form / Last transformation', 'Anime', 2),
('完全体', 'Kanzentai', 'Perfect form / Complete form', 'Anime', 2),
('真の姿', 'Shin no sugata', 'True form / True appearance', 'Anime', 2),

-- ── Military / Organization (軍・組織) ────────────────────────────
('解放軍', 'Kaihougun', 'Liberation army / Freedom fighters', 'Battle', 2),
('革命軍', 'Kakumeigunta', 'Revolutionary army / Rebel forces', 'Battle', 2),
('親衛隊', 'Shin''eitai', 'Personal guard / Royal guard / Elite bodyguard', 'Battle', 2),
('精鋭', 'Seiei', 'Elite / Elite unit / The best soldiers', 'Battle', 2),
('先遣隊', 'Senkentai', 'Advance party / Vanguard unit', 'Battle', 2),
('遠征隊', 'Enseitai', 'Expedition team / Expeditionary force', 'Battle', 2),
('特殊部隊', 'Tokushu butai', 'Special forces / Spec ops', 'Battle', 2),
('遊撃隊', 'Yugekitai', 'Guerrilla unit / Raiding party', 'Battle', 2),
('総司令', 'Soushirei', 'Supreme commander / Commander in chief', 'Battle', 2),
('元帥', 'Gensui', 'Field marshal / Fleet admiral', 'Battle', 2),
('将軍', 'Shougun', 'General / Shogun / Military leader', 'Battle', 3),
('大将', 'Taishou', 'Admiral / General / Supreme commander', 'Battle', 3),
('見習い', 'Minarai', 'Apprentice / Trainee / Novice', 'Anime', 3),
('新米', 'Shinmai', 'Rookie / Newbie / Greenhorn', 'Anime', 3),
('風紀委員', 'Fuuki iin', 'Disciplinary committee / Hall monitor', 'School', 3),

-- ── Character Roles II (役職Ⅱ) ───────────────────────────────────
('皇后', 'Kougou', 'Empress / Queen consort', 'Fantasy', 2),
('弓使い', 'Yumitsukai', 'Archer / Bow user', 'Fantasy', 3),
('槍使い', 'Yaritsukai', 'Spearman / Lance user', 'Fantasy', 3),
('錬金術師', 'Renkinjutsushi', 'Alchemist', 'Fantasy', 2),
('薬師', 'Kusushi', 'Herbalist / Apothecary / Medicine maker', 'Fantasy', 3),
('職人', 'Shokunin', 'Craftsman / Artisan / Tradesperson', 'Fantasy', 3),
('船員', 'Sen''in', 'Crew member / Sailor / Seafarer', 'Anime', 3),
('料理人', 'Ryourinin', 'Cook / Chef', 'Everyday', 3),
('副団長', 'Fukudanchou', 'Vice commander / Deputy captain', 'Battle', 2),
('見張り', 'Mihari', 'Lookout / Watchman / Sentinel', 'Battle', 3),
('番人', 'Bannin', 'Guardian / Gatekeeper / Warden', 'Fantasy', 3),
('征服者', 'Seifukusha', 'Conqueror / Subjugator', 'Anime', 2),
('放浪者', 'Hourousha', 'Wanderer / Drifter / Vagabond', 'Anime', 2),
('生存者', 'Seizonsha', 'Survivor', 'Anime', 3),
('挑戦者', 'Chousenshia', 'Challenger', 'Anime', 3),
('勝者', 'Shousha', 'Winner / Victor / Champion', 'Anime', 3),
('孤児', 'Koji', 'Orphan', 'Anime', 3),

-- ── Family (家族) ─────────────────────────────────────────────────
('父', 'Chichi', 'Father / Dad', 'Everyday', 5),
('母', 'Haha', 'Mother / Mom', 'Everyday', 5),
('兄', 'Ani', 'Older brother', 'Everyday', 5),
('姉', 'Ane', 'Older sister', 'Everyday', 5),
('弟', 'Otouto', 'Younger brother', 'Everyday', 5),
('妹', 'Imouto', 'Younger sister', 'Everyday', 5),
('息子', 'Musuko', 'Son', 'Everyday', 4),
('娘', 'Musume', 'Daughter / Girl', 'Everyday', 4),
('孫', 'Mago', 'Grandchild', 'Everyday', 4),
('祖父', 'Sofu', 'Grandfather / Grandpa', 'Everyday', 4),
('祖母', 'Sobo', 'Grandmother / Grandma', 'Everyday', 4),

-- ── Supernatural / Magic II (超自然Ⅱ) ────────────────────────────
('祝福', 'Shukufuku', 'Blessing / Divine blessing / Benediction', 'Fantasy', 3),
('神秘', 'Shinpi', 'Mystery / Mystical / The divine unknown', 'Fantasy', 3),
('不老', 'Furou', 'Never aging / Immortality of youth', 'Fantasy', 2),
('精霊界', 'Seireiikai', 'Spirit world / Realm of spirits', 'Fantasy', 2),
('古代文明', 'Kodai bunmei', 'Ancient civilization / Lost civilization', 'Fantasy', 2),

-- ── Emotions / Traits II (感情・性格Ⅱ) ───────────────────────────
('不信', 'Fushin', 'Distrust / Suspicion / Doubt', 'Emotions', 3),
('不幸', 'Fukou', 'Unhappiness / Misfortune / Ill fate', 'Emotions', 3),
('平静', 'Heisei', 'Composure / Calm / Unruffled', 'Emotions', 2),
('熱意', 'Netsui', 'Enthusiasm / Eagerness / Zeal', 'Emotions', 2),
('正直', 'Shoujiki', 'Honest / Straightforward / Truthful', 'Emotions', 3),
('天真爛漫', 'Tenshin ranman', 'Carefree and innocent / Naturally cheerful', 'Emotions', 2),
('強欲', 'Gouyoku', 'Greed / Covetousness / Avarice', 'Emotions', 2),
('向上心', 'Koushin', 'Drive to improve / Ambition / Eagerness to grow', 'Emotions', 2),
('自尊心', 'Jisonshin', 'Self-respect / Self-esteem / Pride', 'Emotions', 2),
('優越感', 'Yuuetsuukan', 'Superiority complex / Feeling superior', 'Emotions', 2),
('劣等感', 'Retstoukan', 'Inferiority complex / Feeling inferior', 'Emotions', 2),
('自慢', 'Jiman', 'Bragging / Boasting / Source of pride', 'Emotions', 3),
('反省', 'Hansei', 'Self-reflection / Reconsidering / Remorse', 'Emotions', 3),
('贖罪', 'Shokuzai', 'Atonement / Making amends / Expiation', 'Emotions', 2),
('救済', 'Kyuusai', 'Salvation / Rescue / Redemption', 'Emotions', 2),
('恩', 'On', 'Grace / Debt of gratitude / A favor owed', 'Emotions', 3),
('恩返し', 'Ongaeshi', 'Returning a favor / Repaying kindness', 'Emotions', 3),
('復讐心', 'Fukushuushin', 'Desire for revenge / Vengeful heart', 'Emotions', 2),
('直感', 'Chokkan', 'Intuition / Gut feeling / Sixth sense', 'Emotions', 3),
('決断力', 'Ketsudan ryoku', 'Decisiveness / Power of decision', 'Emotions', 2),
('責任感', 'Sekinin kan', 'Sense of responsibility / Duty', 'Emotions', 2),
('犠牲心', 'Gisei shin', 'Spirit of sacrifice / Willingness to sacrifice', 'Emotions', 2),
('優しさ', 'Yasashisa', 'Kindness / Gentleness / Warmth', 'Emotions', 3)

ON CONFLICT (japanese) DO NOTHING;
